### ISSUE TITLE
Error while deploying:  bad substitution

### ISSUE THREAD

**Issue by kapik** [greenled/portainer-stack-utils#16]
Hey !

I have an issue when I try to deploy:

```
./psu: line 290: bad substitution: no closing `}' in "${docker_compose_file_content//"/'\"'}"
```

I share my `docker-compose.yml` file: 

```yaml
version: '2'

networks:
  default:

services:

  api:
    image: ...
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    networks:
      default:
        aliases:
          - api

  front:
    image: ...
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
    networks:
      default:
        aliases:
          - front

```

Do you have any solution for that ?
Thank for your help :)
